### ISSUE TITLE
can't use with parcel-plugin-typescript

### ISSUE THREAD

**Issue by csvwolf** [lc60005457/parcel-plugin-vue#1]
If I use parcel-plugin-vue only like:

```javascript
// index.js
import Vue from 'vue'
import App from './app.vue'
new Vue({
  el: '#app',
  render: h => h(App)
})
```

app.vue:

```vue
<template>
  <section class="app">
    <h1>Hello World</h1>
  </section>
</template>
```

But when I change it to `index.ts`, there is an error:

```
Uncaught TypeError: Cannot read property 'split' of undefined
```

in `version = Vue.version.split('.').map(Number)`

Is there something wrong with my config?

Waiting for response. THX anyway!

**Comment by BoltDoggy** [comment]
@csvwolf Maybe you need a `tsconfig.json`

```
{
  "compilerOptions": {
    "target": "es5",
    "strict": true,
    "module": "es2015",
    "moduleResolution": "node"
  }
}
```

I find it in https://cn.vuejs.org/v2/guide/typescript.html

You should show your all code or repo url.

**Comment by csvwolf** [comment]
Thank you for your response @lc60005457. I tried the tsconfig and not work.

Here is my repo for the problem: https://github.com/csvwolf/parcel-test

**Comment by BoltDoggy** [comment]
@csvwolf See ~~https://github.com/lc60005457/parcel-test~~ (deleted)

I just add `"dev": "rm -rf .cache && rm -rf dist && parcel index.html",` in

```
  "scripts": {
    "dev": "rm -rf .cache && rm -rf dist && parcel index.html",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

to run `npm run dev` instead of run `rm -rf .cache && rm -rf dist && parcel index.html`

## The Reason

I guess that the plugin for 'typescript' extended and overloaded the 'parcel', but the global parcel is not be overloaded.

In your dist code 'another-crayfish-lite.js' (Maybe 7535:0 maybe other)

`},{"./app.vue":3,"vue":3}],0:[function(require,module,exports) {`

The './app.vue' moduleId eq The 'vue' moduleId.

But my plugin for 'vue' works OK with ts(parcel official).

## Other Error

And See https://github.com/lc60005457/parcel-vue-demo/tree/feature/plugin-typescript#used-with-parcel-plugin-typescript

> The log show Cannot find module './index.vue'.
>
> The Result of browser is OK!
>
> It's that the plugin for 'typescript' can't find '*.vue'.
>
> In 'ts-loader', that has a 'appendTsSuffixTo' option can used for '*.vue'.
> 
> More in https://github.com/TypeStrong/ts-loader#appendtsxsuffixto-regexp-default.

**Comment by fathyb** [comment]
Hey @lc60005457, I'm the maintainer of the TypeScript plugin and I'm still trying to figure out why is this happening, do you think it crashes because I override some Parcel stuff? Thanks.

edit: nevermind I've just understand they are two different errors, I will implement the `ts-loader` behaviour as you said.

And you are right for the error, I extend Parcel but this should be fixed in the new plugin release where I don't touch Parcel at all. The workaround is to just add `parcel-bundler` to the dependencies for now.

**Comment by csvwolf** [comment]
Thank you two @lc60005457 @fathyb . It works well now

**Comment by csvwolf** [comment]
@lc60005457 @fathyb While another question: in vuejs there is a `@types/vue` include, it seems I don't need to config for vue:

```
This is a stub types definition for vuejs (https://github.com/vuejs/vue). vuejs provides its own type definitions, so you don't need @types/vue installed!
```

Why I need to code like that:

```
declare module '*.vue'
```
